development:
  clients:
    default:
      database: jobify_dev
      hosts:
        - 0.0.0.0:27017
      options:
        server_selection_timeout: 1
        user: "mongo"
        password: "mongo"

test:
  clients:
    default:
      database: jobify_test
      hosts:
        - 0.0.0.0:27017
      options:
        server_selection_timeout: 1
        user: "mongo"
        password: "mongo"
